name = "uxshari-workers"
main = "src/index.js"
compatibility_date = "2024-11-01"

[vars]
GCP_PROJECT_ID = "uxshari-670fd"

# Cron Triggers - runs cleanup every 15 minutes
[triggers]
crons = ["*/15 * * * *"]